/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria conversa vazia (aguarda primeira mensagem)
         * @description Abre uma conversa em QUALIFICANDO e devolve a saudação canônica
         *     (spec §6.1). Correlation ID opcional via header (Etapa 6 §2).
         */
        post: operations["criarConversa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        /**
         * Timeline completa (PII mascarada) — rastreabilidade total
         * @description Reconstitui a conversa: mensagens, eventos (seq ordenado), cotações,
         *     handoff. Toda saída passa pelo masking §3 (NFR-12).
         */
        get: operations["obterConversa"];
        put?: never;
        post?: never;
        /**
         * Direito à eliminação (LGPD) — apaga conversa e eventos em cascata
         * @description Requer ADMIN_TOKEN (Etapa 10 §3). Apaga a conversa e todo o histórico
         *     associado (cascata da Etapa 8).
         */
        delete: operations["apagarConversa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: {
                /** @description Retentativa com a mesma chave (janela 2 min) devolve o turno original (replay) */
                "Idempotency-Key"?: string;
                /** @description UUID v4 do client; ecoado no problem+json e nos logs */
                "X-Correlation-Id"?: string;
            };
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Um turno do Lead → resposta síncrona do Agente
         * @description Pior caso ~8s (LLM + 3 tentativas no legado) — client front usa timeout
         *     de 15s. Estados intermediários chegam como `eventos` do turno.
         *     Em `HANDOFF`/terminal o Agente responde idempotente (spec §1.3).
         */
        post: operations["enviarMensagem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/export": {
        parameters: {
            query?: {
                fmt?: "json" | "md";
            };
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        /**
         * Log de execução exportável (entregável do desafio) — PII mascarada
         * @description fmt=json devolve a timeline; fmt=md devolve markdown legível com o
         *     correlation id (Etapa 6 §6). É o artefato "log de execução" da entrega.
         */
        get: operations["exportarConversa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fila de handoffs pendentes (ordenada por criação)
         * @description Conversas transferidas a vendedor humano, com motivo (enum §5.3) e
         *     resumo mascarado. Consumida pela página /handoffs do front.
         */
        get: operations["listarHandoffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saúde do agente e do legado (ping cacheado 30s)
         * @description Sempre 200 com estado detalhado; legado degradado não derruba o agente
         *     (degradação graceful — etapa-6 §5).
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 01J8Z9C3K5M7P9R2T4V6W8YBAA */
        Ulid: string;
        /** @enum {string} */
        EstadoConversa: "QUALIFICANDO" | "CONFIRMANDO" | "COTANDO" | "COTACAO_APRESENTADA" | "OBJECAO" | "HANDOFF" | "ENCERRADA_GANHO_EM_ANDAMENTO" | "ENCERRADA_PERDIDO_INELIGIVEL" | "ENCERRADA_PERDIDO" | "ENCERRADA_SEM_RESPOSTA";
        /**
         * @description Enum de código — nunca texto livre (spec §5.3)
         * @enum {string}
         */
        MotivoHandoff: "aceite_fechamento" | "inelegivel_contestado" | "objecao_preco" | "preferencia_humana" | "falha_tecnica" | "fora_escopo";
        /** @enum {string} */
        TipoEvento: "conversation_started" | "message_in" | "message_out" | "intent_detected" | "lead_qualified" | "pre_check_failed" | "quote_requested" | "quote_attempt_failed" | "circuit_state_changed" | "quote_succeeded" | "quote_presented" | "quote_refused" | "objection_raised" | "handoff_requested" | "retry_scheduled" | "price_guard_violation" | "llm_unavailable" | "conversation_ended";
        ConversaCriada: {
            conversation_id: components["schemas"]["Ulid"];
            estado: components["schemas"]["EstadoConversa"];
            /** Format: date-time */
            criada_em: string;
        };
        /** @description Texto OU mídia (marcador) — XOR */
        MensagemIn: {
            /** @description Fala do Lead (PT-BR livre) */
            text: string;
        } | {
            /** @enum {string} */
            media_type: "image" | "audio" | "document";
            /** @example [documento] CNH_frente.pdf */
            media_marker: string;
        };
        MessageOut: {
            /** @enum {string} */
            role: "lead" | "agente" | "vendedor";
            /** @enum {string} */
            tipo: "text" | "image" | "audio" | "document";
            /** @description PII mascarada (spec §3) */
            texto: string;
            /** Format: date-time */
            criado_em: string;
        };
        EventoOut: {
            seq: number;
            type: components["schemas"]["TipoEvento"];
            /** @description Payload mascarado */
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            criado_em: string;
        };
        ProRata: {
            dias_no_mes: number;
            dias_cobrados: number;
            valor_primeiro_pagamento: number;
        };
        QuoteView: {
            quote_id: components["schemas"]["Ulid"];
            /** @enum {string} */
            plano_id: "essencial" | "completo" | "premium";
            plano_nome: string;
            /** @description Byte a byte igual ao apresentado ao Lead (NFR-09) */
            premio_mensal: number;
            franquia: number;
            coberturas: string[];
            multiplicadores: {
                faixa_etaria: number;
                idade_veiculo: number;
                regiao: number;
            };
            carencia: {
                coberturas: string[];
                dias: number;
            };
            pro_rata?: null | components["schemas"]["ProRata"];
            /** @constant */
            moeda: "BRL";
            tentativas: number;
            /** @description Duração total da cotação (todas as tentativas) */
            duracao_ms: number;
        };
        HandoffView: {
            id: components["schemas"]["Ulid"];
            conversation_id: components["schemas"]["Ulid"];
            motivo: components["schemas"]["MotivoHandoff"];
            /** @description Contexto p/ Vendedor (PII mascarada) */
            resumo: string;
            /** Format: date-time */
            criado_em: string;
            /** @enum {string} */
            status: "pendente" | "em_atendimento" | "concluido";
        };
        TurnoResponse: {
            conversation_id: components["schemas"]["Ulid"];
            estado: components["schemas"]["EstadoConversa"];
            reply: components["schemas"]["MessageOut"];
            eventos: components["schemas"]["EventoOut"][];
            cotacao?: null | components["schemas"]["QuoteView"];
            handoff?: null | components["schemas"]["HandoffView"];
        };
        Timeline: {
            conversation_id: components["schemas"]["Ulid"];
            estado: components["schemas"]["EstadoConversa"];
            dados_qualificados?: null | {
                veiculo_texto?: string;
                veiculo_ano?: number;
                idade?: number;
                /**
                 * @description Sempre mascarado na saída
                 * @example 01***-***
                 */
                cep?: string;
            };
            mensagens: components["schemas"]["MessageOut"][];
            eventos: components["schemas"]["EventoOut"][];
            cotacoes: components["schemas"]["QuoteView"][];
            handoff?: null | components["schemas"]["HandoffView"];
            /** Format: date-time */
            criada_em: string;
            /** Format: date-time */
            atualizada_em: string;
        };
        Health: {
            /** @enum {string} */
            agent: "ok";
            /** @enum {string} */
            legado: "ok" | "degradado";
            versao: string;
        };
        /**
         * @description RFC 7807 + extensão correlation_id (Etapa 6)
         * @example {
         *       "type": "https://autoseguro.dev/problems/payload-invalido",
         *       "title": "Payload inválido",
         *       "status": 422,
         *       "detail": "text e media_marker são mutuamente exclusivos."
         *     }
         */
        Problem: {
            /**
             * Format: uri
             * @description Código estável = slug final da URI
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /**
             * Format: uuid
             * @description Eco do X-Correlation-Id do client ou gerado pelo server — exibido na UI como código de suporte
             */
            correlation_id?: string;
        };
    };
    responses: {
        /** @description Erro RFC 7807 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ConversationId: components["schemas"]["Ulid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    criarConversa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversa criada em QUALIFICANDO */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversaCriada"];
                };
            };
            429: components["responses"]["Problem"];
        };
    };
    obterConversa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timeline com mensagens, eventos, cotações e handoff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    apagarConversa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Apagada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    enviarMensagem: {
        parameters: {
            query?: never;
            header?: {
                /** @description Retentativa com a mesma chave (janela 2 min) devolve o turno original (replay) */
                "Idempotency-Key"?: string;
                /** @description UUID v4 do client; ecoado no problem+json e nos logs */
                "X-Correlation-Id"?: string;
            };
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MensagemIn"];
            };
        };
        responses: {
            /** @description Turno processado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnoResponse"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    exportarConversa: {
        parameters: {
            query?: {
                fmt?: "json" | "md";
            };
            header?: never;
            path: {
                id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artefato de export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                    "text/markdown": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listarHandoffs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fila */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["HandoffView"][];
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sempre 200 com estado detalhado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
